name: Run Python Script
on: [push, workflow_dispatch] 
jobs: 
  run-script:
    run-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/checkout@v3
        with: 
          python-version: "3.4"
      - name: Run script 
        run: python script.py
